#!/usr/bin/env python3
"""
generate_validation_artifacts.py

ISAS 2026 Challenge - Team Prayan

Purpose
-------
Regenerate the validation artifacts shown/reported for the final selected
system directly from the CSV files produced by:

    phase24_fresh_cross_protocol_benchmark.py

This script DOES NOT train a model and DOES NOT use the hidden Apr14 labels.
It reads only development-data evaluation outputs generated by the benchmark.

Primary evaluation reconstructed here
-------------------------------------
MethodKey   : ensemble_class_aware
ProtocolKey : forward
Scope       : pooled

This corresponds to the final selected multi-resolution RF-XGBoost system
under strict expanding-forward validation.

Generated files
---------------
1. strict_forward_confusion_matrix_counts.csv
2. strict_forward_confusion_matrix_normalized.csv
3. strict_forward_confusion_matrix.png
4. strict_forward_classification_report.csv
5. strict_forward_classification_figure.png
6. strict_forward_basic_vs_final_f1.csv
7. strict_forward_basic_vs_final_f1.png
8. strict_forward_metrics_summary.csv

The script performs consistency checks before producing the files. In
particular, metrics reconstructed from the pooled confusion matrix must agree
with phase24_protocol_summary_*.csv and the per-class metrics must agree with
phase24_perclass_summary_*.csv.
"""

from __future__ import annotations

import argparse
from pathlib import Path
import glob
import sys

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt


OFFICIAL_CLASSES = [
    "501", "502", "503", "505", "506", "508", "510", "511", "512", "513",
    "515", "516", "517", "518", "520", "521", "522", "523",
    "cafeteria", "cleaning", "hallway", "kitchen", "nurse station",
]

FINAL_METHOD = "ensemble_class_aware"
BASELINE_METHOD = "rf_basic10"
PROTOCOL = "forward"


def latest_file(directory: Path, pattern: str) -> Path:
    matches = sorted(directory.glob(pattern))
    if not matches:
        raise FileNotFoundError(
            f"No file matching {pattern!r} was found in {directory}"
        )
    return matches[-1]


def safe_divide(num, den):
    num = np.asarray(num, dtype=float)
    den = np.asarray(den, dtype=float)
    return np.divide(
        num,
        den,
        out=np.zeros_like(num, dtype=float),
        where=den != 0,
    )


def metrics_from_confusion(cm: np.ndarray):
    cm = np.asarray(cm, dtype=float)
    tp = np.diag(cm)
    true_support = cm.sum(axis=1)
    pred_support = cm.sum(axis=0)

    precision = safe_divide(tp, pred_support)
    recall = safe_divide(tp, true_support)
    f1 = safe_divide(2.0 * precision * recall, precision + recall)

    total = true_support.sum()
    accuracy = float(tp.sum() / total)
    macro_f1 = float(f1.mean())
    weighted_f1 = float(np.sum(f1 * true_support) / total)

    return {
        "precision": precision,
        "recall": recall,
        "f1": f1,
        "true_support": true_support.astype(int),
        "pred_support": pred_support.astype(int),
        "accuracy": accuracy,
        "macro_f1": macro_f1,
        "weighted_f1": weighted_f1,
        "n": int(total),
    }


def assert_close(name: str, got: float, expected: float, tol: float = 1e-10):
    if not np.isclose(got, expected, rtol=0.0, atol=tol):
        raise RuntimeError(
            f"Consistency check failed for {name}: "
            f"reconstructed={got:.15f}, benchmark={expected:.15f}"
        )


def main():
    parser = argparse.ArgumentParser(
        description="Regenerate Prayan strict-forward validation artifacts "
                    "from Phase 24 benchmark CSV outputs."
    )
    parser.add_argument(
        "--input-dir",
        type=Path,
        default=Path("."),
        help="Directory containing phase24_* CSV outputs.",
    )
    parser.add_argument(
        "--output-dir",
        type=Path,
        default=Path("results"),
        help="Directory in which generated artifacts are written.",
    )
    args = parser.parse_args()

    input_dir = args.input_dir.resolve()
    output_dir = args.output_dir.resolve()
    output_dir.mkdir(parents=True, exist_ok=True)

    confusion_path = latest_file(
        input_dir, "phase24_confusion_detail_*.csv"
    )
    perclass_path = latest_file(
        input_dir, "phase24_perclass_summary_*.csv"
    )
    protocol_path = latest_file(
        input_dir, "phase24_protocol_summary_*.csv"
    )
    support_path = latest_file(
        input_dir, "phase24_class_support_*.csv"
    )

    print("Using:")
    print("  Confusion :", confusion_path)
    print("  Per-class :", perclass_path)
    print("  Protocol  :", protocol_path)
    print("  Support   :", support_path)

    confusion = pd.read_csv(confusion_path)
    perclass = pd.read_csv(perclass_path)
    protocol = pd.read_csv(protocol_path)
    support = pd.read_csv(support_path)

    # -----------------------------------------------------------------
    # Final selected system: pooled strict-forward confusion matrix
    # -----------------------------------------------------------------
    final_conf = confusion[
        (confusion["MethodKey"] == FINAL_METHOD)
        & (confusion["ProtocolKey"] == PROTOCOL)
        & (confusion["Scope"] == "pooled")
    ].copy()

    if len(final_conf) != len(OFFICIAL_CLASSES) ** 2:
        raise RuntimeError(
            "Expected exactly 23 x 23 pooled confusion rows for the final "
            f"system; found {len(final_conf)}."
        )

    cm_counts = (
        final_conf.pivot(
            index="True_Class",
            columns="Pred_Class",
            values="Count",
        )
        .reindex(index=OFFICIAL_CLASSES, columns=OFFICIAL_CLASSES)
        .fillna(0)
        .astype(int)
    )

    if cm_counts.isna().any().any():
        raise RuntimeError("Confusion matrix contains missing entries.")

    m = metrics_from_confusion(cm_counts.to_numpy())

    benchmark_row = protocol[
        (protocol["MethodKey"] == FINAL_METHOD)
        & (protocol["ProtocolKey"] == PROTOCOL)
    ]

    if len(benchmark_row) != 1:
        raise RuntimeError(
            "Expected one final-system strict-forward row in protocol summary."
        )

    benchmark_row = benchmark_row.iloc[0]

    assert_close("Macro_F1", m["macro_f1"], float(benchmark_row["Macro_F1"]))
    assert_close(
        "Weighted_F1",
        m["weighted_f1"],
        float(benchmark_row["Weighted_F1"]),
    )
    assert_close("Accuracy", m["accuracy"], float(benchmark_row["Accuracy"]))

    if int(round(float(benchmark_row["Eval_N"]))) != m["n"]:
        raise RuntimeError(
            f"Eval_N mismatch: reconstructed={m['n']}, "
            f"benchmark={benchmark_row['Eval_N']}"
        )

    # -----------------------------------------------------------------
    # Confusion matrix tables
    # -----------------------------------------------------------------
    cm_counts.index.name = "True_Class"
    cm_counts.to_csv(
        output_dir / "strict_forward_confusion_matrix_counts.csv"
    )

    row_sums = cm_counts.sum(axis=1).replace(0, np.nan)
    cm_norm = cm_counts.div(row_sums, axis=0).fillna(0.0)
    cm_norm.index.name = "True_Class"
    cm_norm.to_csv(
        output_dir / "strict_forward_confusion_matrix_normalized.csv"
    )

    # -----------------------------------------------------------------
    # Classification report rebuilt from confusion matrix
    # -----------------------------------------------------------------
    report = pd.DataFrame({
        "Class": OFFICIAL_CLASSES,
        "Precision": m["precision"],
        "Recall": m["recall"],
        "F1": m["f1"],
        "Support": m["true_support"],
        "Predicted_Support": m["pred_support"],
    })

    # Cross-check against the per-class summary created by Phase 24.
    pc_final = perclass[
        (perclass["MethodKey"] == FINAL_METHOD)
        & (perclass["ProtocolKey"] == PROTOCOL)
    ].copy()

    if len(pc_final) != len(OFFICIAL_CLASSES):
        raise RuntimeError(
            "Expected 23 final-system per-class rows; "
            f"found {len(pc_final)}."
        )

    pc_final = pc_final.set_index("Class").reindex(OFFICIAL_CLASSES)

    for i, cls in enumerate(OFFICIAL_CLASSES):
        assert_close(
            f"{cls} Precision",
            report.loc[i, "Precision"],
            float(pc_final.loc[cls, "Precision"]),
        )
        assert_close(
            f"{cls} Recall",
            report.loc[i, "Recall"],
            float(pc_final.loc[cls, "Recall"]),
        )
        assert_close(
            f"{cls} F1",
            report.loc[i, "F1"],
            float(pc_final.loc[cls, "F1"]),
        )

        if int(report.loc[i, "Support"]) != int(
            round(float(pc_final.loc[cls, "Support_Mean"]))
        ):
            raise RuntimeError(f"{cls} support mismatch.")

    report.to_csv(
        output_dir / "strict_forward_classification_report.csv",
        index=False,
    )

    metrics_summary = pd.DataFrame([{
        "MethodKey": FINAL_METHOD,
        "ProtocolKey": PROTOCOL,
        "Macro_F1": m["macro_f1"],
        "Weighted_F1": m["weighted_f1"],
        "Accuracy": m["accuracy"],
        "Eval_N": m["n"],
        "Classes": len(OFFICIAL_CLASSES),
    }])
    metrics_summary.to_csv(
        output_dir / "strict_forward_metrics_summary.csv",
        index=False,
    )

    # -----------------------------------------------------------------
    # Figure 1: true-normalized confusion matrix
    # -----------------------------------------------------------------
    fig, ax = plt.subplots(figsize=(11.5, 10.0))
    image = ax.imshow(cm_norm.to_numpy(), aspect="auto")

    ax.set_xticks(np.arange(len(OFFICIAL_CLASSES)))
    ax.set_xticklabels(OFFICIAL_CLASSES, rotation=90, fontsize=7)
    ax.set_yticks(np.arange(len(OFFICIAL_CLASSES)))
    ax.set_yticklabels(OFFICIAL_CLASSES, fontsize=7)

    ax.set_xlabel("Predicted location")
    ax.set_ylabel("True location")
    ax.set_title(
        "Final selected system: pooled strict-forward confusion matrix\n"
        "(development data, normalized by true class)"
    )

    cbar = fig.colorbar(image, ax=ax)
    cbar.set_label("Fraction of true-class samples")

    fig.tight_layout()
    fig.savefig(
        output_dir / "strict_forward_confusion_matrix.png",
        dpi=300,
        bbox_inches="tight",
    )
    fig.savefig(
        output_dir / "strict_forward_confusion_matrix.pdf",
        bbox_inches="tight",
    )
    plt.close(fig)

    # -----------------------------------------------------------------
    # Figure 2: classification metrics for every class
    # -----------------------------------------------------------------
    plot_report = report.copy()
    plot_report["Display"] = (
        plot_report["Class"]
        + " (n="
        + plot_report["Support"].map(lambda x: f"{int(x):,}")
        + ")"
    )

    y = np.arange(len(plot_report))
    offset = 0.22

    fig, ax = plt.subplots(figsize=(10.5, 9.0))
    ax.scatter(
        plot_report["Precision"],
        y - offset,
        marker="o",
        label="Precision",
    )
    ax.scatter(
        plot_report["Recall"],
        y,
        marker="s",
        label="Recall",
    )
    ax.scatter(
        plot_report["F1"],
        y + offset,
        marker="D",
        label="F1",
    )

    ax.set_yticks(y)
    ax.set_yticklabels(plot_report["Display"], fontsize=8)
    ax.invert_yaxis()
    ax.set_xlim(-0.02, 1.02)
    ax.set_xlabel("Score")
    ax.set_ylabel("Location class (strict-forward support)")
    ax.set_title(
        "Final selected system: per-class classification metrics\n"
        "(pooled strict-forward development evaluation)"
    )
    ax.grid(axis="x", alpha=0.25)
    ax.legend(loc="lower right")
    fig.tight_layout()

    fig.savefig(
        output_dir / "strict_forward_classification_figure.png",
        dpi=300,
        bbox_inches="tight",
    )
    fig.savefig(
        output_dir / "strict_forward_classification_figure.pdf",
        bbox_inches="tight",
    )
    plt.close(fig)

    # -----------------------------------------------------------------
    # Figure 3: exact paper-style Basic RF vs final per-class F1 comparison
    # -----------------------------------------------------------------
    pc_base = perclass[
        (perclass["MethodKey"] == BASELINE_METHOD)
        & (perclass["ProtocolKey"] == PROTOCOL)
    ].copy()

    if len(pc_base) != len(OFFICIAL_CLASSES):
        raise RuntimeError(
            "Expected 23 Basic-RF strict-forward per-class rows; "
            f"found {len(pc_base)}."
        )

    pc_base = pc_base.set_index("Class").reindex(OFFICIAL_CLASSES)
    pc_final_idx = pc_final.copy()

    support_idx = support.set_index("Class")["Total_Seconds"]

    comparison = pd.DataFrame({
        "Class": OFFICIAL_CLASSES,
        "Support": [int(support_idx.loc[c]) for c in OFFICIAL_CLASSES],
        "Basic_RF_F1": [
            float(pc_base.loc[c, "F1"]) for c in OFFICIAL_CLASSES
        ],
        "Final_System_F1": [
            float(pc_final_idx.loc[c, "F1"]) for c in OFFICIAL_CLASSES
        ],
    })
    comparison["Delta_F1"] = (
        comparison["Final_System_F1"] - comparison["Basic_RF_F1"]
    )

    comparison.to_csv(
        output_dir / "strict_forward_basic_vs_final_f1.csv",
        index=False,
    )

    plot_df = comparison.sort_values(
        ["Delta_F1", "Final_System_F1", "Support"],
        ascending=[False, False, False],
    ).reset_index(drop=True)

    plot_df["Display"] = (
        plot_df["Class"]
        + " (n="
        + plot_df["Support"].map(lambda x: f"{int(x):,}")
        + ")"
    )
    y = np.arange(len(plot_df))
    marker_size = 28 + 17 * np.log10(
        plot_df["Support"].to_numpy(dtype=float) + 1
    )

    fig, ax = plt.subplots(figsize=(11.6, 9.1))

    for i, row in plot_df.iterrows():
        ax.plot(
            [row["Basic_RF_F1"], row["Final_System_F1"]],
            [i, i],
            linewidth=1.0,
        )

    ax.scatter(
        plot_df["Basic_RF_F1"],
        y,
        s=marker_size,
        marker="o",
        label="10 s RF baseline",
    )
    ax.scatter(
        plot_df["Final_System_F1"],
        y,
        s=marker_size,
        marker="D",
        label="Final selected system",
    )

    delta_x = 1.075
    for i, row in plot_df.iterrows():
        ax.text(
            delta_x,
            i,
            f"Δ {row['Delta_F1']:+.3f}",
            ha="left",
            va="center",
            fontsize=7.6,
        )

    ax.text(
        delta_x,
        -0.88,
        "ΔF1",
        ha="left",
        va="center",
        fontsize=8.5,
        fontweight="bold",
    )

    ax.set_yticks(y)
    ax.set_yticklabels(plot_df["Display"], fontsize=8)
    ax.invert_yaxis()
    ax.set_xlim(-0.02, 1.22)
    ax.set_xlabel("Per-class F1")
    ax.set_ylabel("Class (total labeled development seconds)")
    ax.set_title(
        "Basic RF vs final selected system under strict-forward evaluation"
    )
    ax.axvline(1.025, linewidth=0.8)
    ax.grid(axis="x", alpha=0.25)
    ax.legend(loc="lower right", fontsize=8)
    fig.tight_layout()

    fig.savefig(
        output_dir / "strict_forward_basic_vs_final_f1.png",
        dpi=300,
        bbox_inches="tight",
    )
    fig.savefig(
        output_dir / "strict_forward_basic_vs_final_f1.pdf",
        bbox_inches="tight",
    )
    plt.close(fig)

    print()
    print("=" * 78)
    print("VALIDATION ARTIFACT REGENERATION: PASS")
    print("=" * 78)
    print(f"Method       : {FINAL_METHOD}")
    print(f"Protocol     : {PROTOCOL} (pooled)")
    print(f"Eval N       : {m['n']:,}")
    print(f"Macro F1     : {m['macro_f1']:.12f}")
    print(f"Weighted F1  : {m['weighted_f1']:.12f}")
    print(f"Accuracy     : {m['accuracy']:.12f}")
    print(f"Output dir   : {output_dir}")
    print()
    print("The confusion matrix and per-class metrics were reconstructed from")
    print("Phase 24 benchmark CSV outputs and matched the benchmark summaries.")
    print("No Apr14 ground-truth labels were used.")


if __name__ == "__main__":
    main()
